globalThis.JEV_CATEGORIES = [
  { id: "plumbing", label: "Plumbing", words: ["plumb", "plumber", "water heater", "drain cleaning", "pipe leak", "sewer"] },
  { id: "hvac", label: "HVAC", words: ["hvac", "air conditioning", "furnace", "heat pump", "ac repair", "air conditioner"] },
  { id: "electrical", label: "Electrical", words: ["electrician", "electrical panel", "rewire", "outlet", "breaker box"] },
  { id: "roofing", label: "Roofing", words: ["roof", "roofing", "shingle", "roofer", "leak in the roof"] },
  { id: "fencing", label: "Fencing", words: ["fence", "fencing", "gate install"] },
  { id: "landscaping", label: "Landscaping", words: ["landscap", "mulch", "hardscape", "lawn design"] },
  { id: "lawn", label: "Lawn care", words: ["lawn", "mowing", "grass cutting", "yard service"] },
  { id: "painting", label: "Painting", words: ["house paint", "painter", "interior paint", "exterior paint"] },
  { id: "flooring", label: "Flooring", words: ["flooring", "hardwood floor", "tile floor", "lvp"] },
  { id: "concrete", label: "Concrete", words: ["concrete", "driveway", "sidewalk pour", "stamped concrete"] },
  { id: "carpentry", label: "Carpentry", words: ["carpenter", "carpentry", "trim work", "cabinet"] },
  { id: "remodel", label: "Remodeling", words: ["remodel", "renovation", "kitchen remodel", "bathroom remodel"] },
  { id: "cleaning", label: "Cleaning", words: ["house cleaning", "maid", "janitorial", "pressure wash", "carpet clean"] },
  { id: "pest", label: "Pest control", words: ["pest", "termite", "exterminator", "rodent"] },
  { id: "garage", label: "Garage doors", words: ["garage door", "garage opener"] },
  { id: "windows", label: "Windows", words: ["window replacement", "window install", "new windows"] },
  { id: "solar", label: "Solar", words: ["solar panel", "solar install", "rooftop solar"] },
  { id: "auto", label: "Auto repair", words: ["auto repair", "mechanic", "brake job", "oil change", "car repair"] },
  { id: "towing", label: "Towing", words: ["tow truck", "towing", "roadside"] },
  { id: "realestate", label: "Real estate", words: ["real estate", "realtor", "listing", "open house", "home for sale"] },
  { id: "property", label: "Property management", words: ["property management", "landlord", "tenant", "rental property"] },
  { id: "construction", label: "Construction", words: ["construction", "general contractor", "job site", "gc "] },
  { id: "handyman", label: "Handyman", words: ["handyman", "odd jobs", "honey do"] },
  { id: "seo", label: "Local SEO", words: ["local seo", "google business", "map pack", "rank on google"] },
  { id: "marketing", label: "Marketing", words: ["marketing", "brand", "campaign", "advertis"] },
  { id: "social", label: "Social media", words: ["social media", "instagram", "content calendar", "tiktok"] },
  { id: "ads", label: "Google Ads", words: ["google ads", "ppc", "adwords", "paid search"] },
  { id: "websites", label: "Websites", words: ["website", "web design", "landing page", "wordpress"] },
  { id: "crm", label: "CRM", words: ["crm", "pipeline", "follow up", "customer relationship"] },
  { id: "smallbiz", label: "Small business", words: ["small business", "shop owner", "main street", "local business"] },
  { id: "leads", label: "Lead generation", words: ["lead gen", "leads", "booked call", "estimate request"] },
  { id: "sales", label: "Sales", words: ["sales call", "closing", "quota", "outbound"] },
  { id: "service", label: "Customer service", words: ["customer service", "support ticket", "client care"] },
  { id: "books", label: "Bookkeeping", words: ["bookkeep", "quickbooks", "invoice", "accounts payable"] },
  { id: "tax", label: "Taxes", words: ["tax return", "accountant", "irs", "write off"] },
  { id: "insurance", label: "Insurance", words: ["insurance", "policy quote", "coverage"] },
  { id: "legal", label: "Legal", words: ["attorney", "lawyer", "contract", "lawsuit"] },
  { id: "hiring", label: "Hiring", words: ["hiring", "we're hiring", "job opening", "apply now"] },
  { id: "restaurant", label: "Restaurants", words: ["restaurant", "menu", "dine", "chef"] },
  { id: "coffee", label: "Coffee", words: ["coffee", "cafe", "espresso", "latte"] },
  { id: "fitness", label: "Fitness", words: ["gym", "workout", "personal train", "fitness"] },
  { id: "health", label: "Health", words: ["clinic", "patient", "healthcare", "doctor"] },
  { id: "dental", label: "Dental", words: ["dentist", "dental", "teeth", "orthodont"] },
  { id: "photo", label: "Photography", words: ["photographer", "photo shoot", "wedding photo"] },
  { id: "wedding", label: "Weddings", words: ["wedding", "bride", "groom", "venue"] },
  { id: "pets", label: "Pets", words: ["dog", "cat", "veterinar", "pet groom", "puppy"] },
  { id: "childcare", label: "Childcare", words: ["daycare", "childcare", "preschool", "babysit"] },
  { id: "moving", label: "Moving", words: ["moving company", "movers", "relocation"] },
  { id: "junk", label: "Junk removal", words: ["junk removal", "haul away", "dumpster"] },
  { id: "trees", label: "Tree service", words: ["tree service", "tree removal", "stump", "arborist"] },
  { id: "pool", label: "Pool service", words: ["pool clean", "pool service", "swimming pool"] }
];

globalThis.JEV_SPAM = [
  "giveaway", "airdrop", "follow back", "f4f", "dm to win", "crypto signal",
  "guaranteed profit", "link in bio", "sponsored", "promoted", "use my code",
  "onlyfans", "double your money"
];
